global:
  scrape_interval: 10s
  evalution_interval: 10s

rule_files:
  - 'alert.yml'

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "alertmanager:9093"

scrape_configs:
  - job_name: 'prometheus'
      metrics_path: '/api/v1/allmetrics'
    params:
      format: [prometheus]
    honor_labels: true
  scrape_interval: 5s
    static_configs:
      - target: ['localhost:9090','cadvisor:8080','node-exporter:9100']

  - job_name: 'application'
  metrics_path: '/metrics'
  scrape_interval: 5s
    static_configs:
      - targets: ['application:3000']

      
