global:
  scrape_interval: 15s
  evalution_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - target: ['localhost:9090']

  - job_name: 'application'
    static_configs:
      - targets: ['application:3000']